function h_fig = createProgressWindow(total_samples, expected_categories)
h_fig = figure('Name', '🎵 System Rozpoznawania Głosu', ...
    'Position', [300, 400, 550, 280], ...  % Zwiększona wysokość na przycisk
    'MenuBar', 'none', 'ToolBar', 'none', ...
    'Resize', 'off', 'NumberTitle', 'off', ...
    'Color', [0.94 0.94 0.94], ...
    'CloseRequestFcn', @(src,evt) closeProgressWindow(src));  % Custom zamknięcie

% Flaga zatrzymania - zapisana w UserData
h_fig.UserData.stop_requested = false;

% Tytuł główny
uicontrol('Style', 'text', ...
    'String', '🎵 Przetwarzanie Danych Audio', ...
    'Position', [20, 230, 510, 30], ...  % Przesunięte w górę
    'FontSize', 16, 'FontWeight', 'bold', ...
    'BackgroundColor', [0.94 0.94 0.94], ...
    'ForegroundColor', [0.2 0.2 0.6]);

% Info o kategoriach
uicontrol('Style', 'text', ...
    'String', sprintf('📊 Kategorii: %d | Próbek: %d', expected_categories, total_samples), ...
    'Position', [20, 200, 510, 20], ...  % Przesunięte w górę
    'FontSize', 11, ...
    'BackgroundColor', [0.94 0.94 0.94]);

% Progress bar container
uicontrol('Style', 'text', ...
    'Position', [20, 170, 510, 20], ...  % Przesunięte w górę
    'BackgroundColor', [0.8 0.8 0.8]);

% Aktualny progress bar
h_fig.UserData.progress_bar = uicontrol('Style', 'text', ...
    'Position', [20, 170, 1, 20], ...  % Przesunięte w górę
    'BackgroundColor', [0.2 0.7 0.2]);

% Tekst procentowy na progress bar
h_fig.UserData.percent_text = uicontrol('Style', 'text', ...
    'String', '0.0%', ...
    'Position', [20, 170, 510, 20], ...  % Przesunięte w górę
    'FontSize', 10, 'FontWeight', 'bold', ...
    'BackgroundColor', 'none', ...
    'ForegroundColor', [1 1 1]);

% Aktualny status
h_fig.UserData.status_text = uicontrol('Style', 'text', ...
    'String', '🔄 Przygotowanie...', ...
    'Position', [20, 140, 510, 20], ...  % Przesunięte w górę
    'FontSize', 11, ...
    'BackgroundColor', [0.94 0.94 0.94], ...
    'HorizontalAlignment', 'left');

% Statystyki
h_fig.UserData.stats_text = uicontrol('Style', 'text', ...
    'String', '✅ Udane: 0 | ❌ Nieudane: 0', ...
    'Position', [20, 110, 510, 20], ...  % Przesunięte w górę
    'FontSize', 10, ...
    'BackgroundColor', [0.94 0.94 0.94], ...
    'HorizontalAlignment', 'left');

% Czas
h_fig.UserData.time_text = uicontrol('Style', 'text', ...
    'String', '⏱️ Czas: 0s', ...
    'Position', [20, 80, 510, 20], ...  % Przesunięte w górę
    'FontSize', 10, ...
    'BackgroundColor', [0.94 0.94 0.94], ...
    'HorizontalAlignment', 'left');

% PRZYCISK ZATRZYMANIA
h_fig.UserData.stop_button = uicontrol('Style', 'pushbutton', ...
    'String', '⏹️ ZATRZYMAJ', ...
    'Position', [200, 30, 150, 35], ...
    'FontSize', 12, 'FontWeight', 'bold', ...
    'BackgroundColor', [0.9 0.3 0.3], ...
    'ForegroundColor', [1 1 1], ...
    'Callback', @(src,evt) stopProcessing(h_fig));

% Zapisz czas rozpoczęcia
h_fig.UserData.start_time = tic;

drawnow;
end