function saveProcessedData(filename, X, Y, labels, successful_loads, failed_loads, ...
    normalize_flag, normalization_status, noise_level, num_samples, use_vowels, use_complex)
% Zapisuje przetworzone dane wraz z metadanymi

save(filename, 'X', 'Y', 'labels', 'successful_loads', 'failed_loads', ...
    'normalize_features_flag', normalize_flag, 'normalization_status', normalization_status, ...
    'noise_level', noise_level, 'num_samples', num_samples, ...
    'use_vowels', use_vowels, 'use_complex', use_complex);
end